require("dotenv").config();
const UserProfile = require("../models/UserProfile");
const { GoogleGenerativeAI } = require("@google/generative-ai");

// BMI Calculator
function calculateBMI(heightCm, weightKg) {
  const heightM = heightCm / 100;
  return Number((weightKg / (heightM * heightM)).toFixed(1));
}

async function recommendHandler(req, res) {
  try {
    const { heightCm, weightKg, age, goal, foodPreference } = req.body;

    if (!heightCm || !weightKg || !age || !goal || !foodPreference) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const bmi = calculateBMI(heightCm, weightKg);

    const prompt = `
Generate a complete personalized diet plan.

User Details:
- Height: ${heightCm} cm
- Weight: ${weightKg} kg
- Age: ${age}
- BMI: ${bmi}
- Goal: ${goal}
- Food Preference: ${foodPreference}

Return structured output using HTML tags:
SUMMARY:
MEAL PLAN (Breakfast, Lunch, Dinner, Snacks with calories):
HYDRATION:
WORKOUT TIP:
`;

    let aiText = "";

    try {
      // Initialize Gemini **inside the function**
      const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
      const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });

      const result = await model.generateContent(prompt);
      aiText = result.response.text();
    } catch (err) {
      console.log("Gemini Error:", err.message);
      aiText = "<p>AI unavailable. Please try again later.</p>";
    }

    // Save to MongoDB
    const profile = new UserProfile({
      heightCm,
      weightKg,
      age,
      goal,
      foodPreference,
      bmi,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: "Generated by Gemini"
      }
    });

    await profile.save();

    res.json({
      success: true,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: ""
      }
    });

  } catch (err) {
    console.error("Server error:", err);
    res.status(500).json({ error: "Server error" });
  }
}

module.exports = { recommendHandler };



