require("dotenv").config();
const UserProfile = require("../models/UserProfile");
const { GoogleGenerativeAI } = require("@google/generative-ai");

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-pro" });

// BMI Calculator
function calculateBMI(heightCm, weightKg) {
  const heightM = heightCm / 100;
  return Number((weightKg / (heightM * heightM)).toFixed(1));
}

async function recommendHandler(req, res) {
  try {
    const { heightCm, weightKg, age, goal, foodPreference } = req.body;

    if (!heightCm || !weightKg || !age || !goal || !foodPreference) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const bmi = calculateBMI(heightCm, weightKg);

    // AI Prompt for Gemini
    const prompt = `
Generate a complete personalized diet plan.

User Details:
- Height: ${heightCm} cm
- Weight: ${weightKg} kg
- Age: ${age}
- BMI: ${bmi}
- Goal: ${goal}
- Food Preference: ${foodPreference}

Return in this exact format using HTML:

SUMMARY:
Short summary + BMI meaning + calories needed per day.

MEAL PLAN:
Breakfast (with calories)
Lunch (with calories)
Dinner (with calories)
Snacks (with calories)

HYDRATION:
Daily water intake.

WORKOUT TIP:
One simple workout suggestion.
`;

    let aiText = "";
    try {
      const result = await model.generateContent(prompt);
      aiText = result.response.text();

    } catch (err) {
      console.log("Gemini AI failed:", err.message);
      aiText = "<p>AI unavailable. Please try again later.</p>";
    }

    // Save to DB
    const profile = new UserProfile({
      heightCm,
      weightKg,
      age,
      goal,
      foodPreference,
      bmi,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: "Generated by Gemini AI"
      }
    });

    await profile.save();

    // Send to frontend
    res.json({
      success: true,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: ""
      }
    });

  } catch (err) {
    console.error("Server error:", err);
    res.status(500).json({ error: "Server error" });
  }
}

module.exports = { recommendHandler };

