require("dotenv").config();
const UserProfile = require("../models/UserProfile");
const OpenAI = require("openai");

// Initialize OpenAI
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

// BMI Calculator
function calculateBMI(heightCm, weightKg) {
  const heightM = heightCm / 100;
  return Number((weightKg / (heightM * heightM)).toFixed(1));
}

async function recommendHandler(req, res) {
  try {
    const { heightCm, weightKg, age, goal, foodPreference } = req.body;

    if (!heightCm || !weightKg || !age || !goal || !foodPreference) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    const bmi = calculateBMI(heightCm, weightKg);

    // AI PROMPT
    const prompt = `
Generate a COMPLETE personalized diet plan.

User Details:
- Height: ${heightCm} cm
- Weight: ${weightKg} kg
- Age: ${age}
- BMI: ${bmi}
- Goal: ${goal}
- Food Preference: ${foodPreference}

Return the result in this EXACT format (HTML allowed):

SUMMARY:
Short summary + BMI meaning + calories user should eat per day.

MEAL PLAN:
Breakfast (with calories)
Lunch (with calories)
Dinner (with calories)
Snacks (with calories)

HYDRATION:
Daily water intake recommendation.

WORKOUT TIP:
1 short workout suggestion.

Make the response friendly and clear.
    `;

    // AI CALL
    let aiText = "";
    try {
      const aiRes = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }]
      });

      aiText = aiRes.choices[0].message.content;
    } catch (err) {
      console.log("AI failed:", err.message);
      aiText = "<p>AI unavailable. Please try again later.</p>";
    }

    // SAVE TO DATABASE
    const profile = new UserProfile({
      heightCm,
      weightKg,
      age,
      goal,
      foodPreference,
      bmi,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: "Generated by AI"
      }
    });

    await profile.save();

    // SEND TO FRONTEND
    res.json({
      success: true,
      recommendation: {
        summary: `Your BMI is ${bmi}`,
        mealsHtml: aiText,
        aiSummary: ""
      }
    });

  } catch (err) {
    console.error("Server error:", err);
    res.status(500).json({ error: "Server error" });
  }
}

module.exports = { recommendHandler };

